# Python基础

In [1]:
# 求余数 % 
a = 9 % 2
a

1

In [2]:
# 整除 //
b = 9 // 2
b

4

# Numpy

In [3]:
import numpy as np
print(np.__version__)

1.23.5


c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [4]:
arr0 = np.array([0, 1, 2, 3])
arr1 = np.array([[0, 1], [2, 3]])
print(arr0)
print(arr1)

[0 1 2 3]
[[0 1]
 [2 3]]


In [25]:
# 生成给定范围的数组，参数分别为start，stop，step
np.arange(0, 10, 0.5)


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [26]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
# 随机矩阵
np.random.rand(3, 3)

array([[0.57984435, 0.35427389, 0.774765  ],
       [0.80404524, 0.17828937, 0.55021331],
       [0.15728546, 0.22626281, 0.37919978]])

In [32]:
# 整数随机矩阵
np.random.randint(1, 10, (3, 3))

array([[4, 3, 3],
       [3, 3, 3],
       [6, 3, 3]])

In [33]:
# 矩阵相乘
arr2 = np.random.randint(1, 10, (3, 2))
arr3 = np.random.randint(1, 10, (2, 3))
arr4 = np.dot(arr2, arr3)
arr4

array([[17, 19,  7],
       [60, 55, 25],
       [50, 39, 21]])

In [34]:
np.max(arr4)

60

In [35]:
np.min(arr4)

7

In [36]:
# 数组行方向的最小值,参数0代表行
np.amin(arr4, 0)

array([17, 19,  7])

In [37]:
# 数组列方向的最小值，参数1代表列
np.amin(arr4, 1)

array([ 7, 25, 21])

In [38]:
# 数组中的中位数
np.median(arr4)

25.0

# Pandas

In [39]:
import pandas as pd
print(pd.__version__)

2.1.1


In [40]:
# 序列
series0 = pd.Series(data=[1, 2, 3], index=['a', 'b', 'c'])
series0

a    1
b    2
c    3
dtype: int64

In [41]:
series0.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [42]:
series0.info()

<class 'pandas.core.series.Series'>
Index: 3 entries, a to c
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0+ bytes


In [44]:
# 数据框
df = pd.DataFrame(arr4, columns=['a', 'b', 'c'])
df

a   b   c
0  17  19   7
1  60  55  25
2  50  39  21

In [46]:
# 提取行
df[0:1]

a   b  c
0  17  19  7

In [47]:
# 提取列
df.a

0    17
1    60
2    50
Name: a, dtype: int32

In [49]:
# 访问数据框中的元素1
df.at[1, 'a']

60

In [51]:
# 访问数据框中的元素2
df.iloc[1:3, 1:3]

b   c
1  55  25
2  39  21