# Python基础

In [10]:
# 求余数 % 
a = 9 % 2
a

1

In [9]:
# 整除 //
b = 9 // 2
b

4

# Numpy

In [12]:
import numpy as np
print(np.__version__)

1.24.3


In [17]:
arr0 = np.array([0, 1, 2, 3])
arr1 = np.array([[0, 1], [2, 3]])
print(arr0)
print(arr1)

[0 1 2 3]
[[0 1]
 [2 3]]


In [47]:
# 生成给定范围的数组，参数分别为start，stop，step
np.arange(0, 10, 0.5)


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [46]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
# 随机矩阵
np.random.rand(3, 3)

array([[0.46612415, 0.69844561, 0.9693205 ],
       [0.14816362, 0.19323206, 0.59168916],
       [0.21836758, 0.00667166, 0.31830862]])

In [44]:
# 整数随机矩阵
np.random.randint(1, 10, (3, 3))

array([[1, 1, 5],
       [2, 9, 3],
       [1, 5, 4]])

In [63]:
# 矩阵相乘
arr2 = np.random.randint(1, 10, (3, 2))
arr3 = np.random.randint(1, 10, (2, 3))
arr4 = np.dot(arr2, arr3)
arr4

array([[94, 76, 74],
       [21, 16, 17],
       [33, 35, 22]])

In [64]:
np.max(arr4)

94

In [65]:
np.min(arr4)

16

In [66]:
# 数组行方向的最小值
np.amin(arr4, 0)

array([21, 16, 17])

In [68]:
# 数组列方向的最小值
np.amin(arr4, 1)

array([74, 16, 22])

In [69]:
# 数组中的中位数
np.median(arr4)

33.0

# Pandas

In [70]:
import pandas as pd
print(pd.__version__)

2.0.1


In [75]:
# 序列
series0 = pd.Series(data=[1, 2, 3], index=['a', 'b', 'c'])
series0

a    1
b    2
c    3
dtype: int64

In [76]:
series0.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [78]:
# 数据框
df = pd.DataFrame(arr4, columns=['a', 'b', 'c'])
df

a   b   c
0  94  76  74
1  21  16  17
2  33  35  22

In [80]:
df[0:1]

a   b   c
0  94  76  74

In [81]:
df.a

0    94
1    21
2    33
Name: a, dtype: int32

In [84]:
df.at[1, 'a']

21

In [86]:
# 访问数据框中的元素
df.iloc[1:3, 1:3]

b   c
1  16  17
2  35  22