# Python基础

In [1]:
# 求余数 % 
a = 9 % 2
a

1

In [2]:
# 整除 //
b = 9 // 2
b

4

# Numpy

In [3]:
import numpy as np
print(np.__version__)

1.23.5


c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [4]:
arr0 = np.array([0, 1, 2, 3])
arr1 = np.array([[0, 1], [2, 3]])
print(arr0)
print(arr1)

[0 1 2 3]
[[0 1]
 [2 3]]


In [5]:
# 生成给定范围的数组，参数分别为start，stop，step
np.arange(0, 10, 0.5)


array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [6]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# 随机矩阵
np.random.rand(3, 3)

array([[0.58499099, 0.75762421, 0.0477063 ],
       [0.89201151, 0.02911909, 0.31597117],
       [0.91029622, 0.75637122, 0.64077589]])

In [9]:
# 整数随机矩阵
np.random.randint(1, 10, (3, 3))

array([[5, 1, 1],
       [2, 3, 9],
       [9, 4, 3]])

In [10]:
# 矩阵相乘
arr2 = np.random.randint(1, 10, (3, 2))
arr3 = np.random.randint(1, 10, (2, 3))
arr4 = np.dot(arr2, arr3)
arr4

array([[73, 25, 63],
       [49, 10, 54],
       [63, 16, 64]])

In [11]:
np.max(arr4)

73

In [12]:
np.min(arr4)

10

In [13]:
# 数组行方向的最小值
np.amin(arr4, 0)

array([49, 10, 54])

In [14]:
# 数组列方向的最小值
np.amin(arr4, 1)

array([25, 10, 16])

In [15]:
# 数组中的中位数
np.median(arr4)

54.0

# Pandas

In [16]:
import pandas as pd
print(pd.__version__)

2.1.1


In [17]:
# 序列
series0 = pd.Series(data=[1, 2, 3], index=['a', 'b', 'c'])
series0

a    1
b    2
c    3
dtype: int64

In [18]:
series0.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [19]:
# 数据框
df = pd.DataFrame(arr4, columns=['a', 'b', 'c'])
df

a   b   c
0  73  25  63
1  49  10  54
2  63  16  64

In [20]:
df[0:1]

a   b   c
0  73  25  63

In [21]:
df.a

0    73
1    49
2    63
Name: a, dtype: int32

In [22]:
df.at[1, 'a']

49

In [23]:
# 访问数据框中的元素
df.iloc[1:3, 1:3]

b   c
1  10  54
2  16  64