# 数据选择

In [1]:
import numpy as np
import pandas as pd

c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
# 一维数组的选择
a = np.array([1,2,3,4,5,6])

print(a[0])
print(a[-1])
print(a[0:2])
print(a[2:])
print(a[0:5:2])

1
6
[1 2]
[3 4 5 6]
[1 3 5]


In [3]:
# 二维数组的选择
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,2])
print(arr[0])
print(arr[:,0])

6
[1 2 3]
[1 4]


In [4]:
# 布尔值索引
bolling = np.array([True,False,False,True,True,False])
a[bolling]

array([1, 4, 5])

In [5]:
arr = np.arange(28).reshape((7,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [6]:
# 二维布尔索引
bolling2 = np.array([True,False,False,True,True,False,False])
arr[bolling2]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
# 花式索引
arr[arr > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [8]:
arr[arr > 14] = 0
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [9]:
# Pandas数据选择
# Series
s = pd.Series(data=[1,2,3,4,5,6],
              index=['a','b','a','a','a','c'])
s

a    1
b    2
a    3
a    4
a    5
c    6
dtype: int64

In [10]:
print(s['a'])
print(s[['b','c']])
print(s['b':'c'])
print(s['b':'c':2])

a    1
a    3
a    4
a    5
dtype: int64
b    2
c    6
dtype: int64
b    2
a    3
a    4
a    5
c    6
dtype: int64
b    2
a    4
c    6
dtype: int64


In [11]:
# DataFrame
df = pd.DataFrame(data=[[22, "北京", "律师" ],
                        [26, "四川成都", "工程师"],
                        [24, "江苏南京", "研究员"]],
                  index=["张某", "李某", "段某"],
                  columns=["age", "籍贯", "职业"])
df

age    籍贯   职业
张某   22    北京   律师
李某   26  四川成都  工程师
段某   24  江苏南京  研究员

In [12]:
print(df['age'], type(df['age']))  # 索引列
print(df['age']['张某'])  # 索引列，行
print(df['age'][0])  # 索引列，行
print(df['age'][df['age'].values == 22])

张某    22
李某    26
段某    24
Name: age, dtype: int64 <class 'pandas.core.series.Series'>
22
22
张某    22
Name: age, dtype: int64


C:\Users\OneRaise\AppData\Local\Temp\ipykernel_10532\1577797780.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df['age'][0])  # 索引列，行


In [13]:
# 这种格式默认是索引列，若想要索引行，必须使用[x:x]的形式
print(df['张某':'李某'])

    age    籍贯   职业
张某   22    北京   律师
李某   26  四川成都  工程师


# 数据合并

In [14]:
# merge()
left = pd.DataFrame({
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame(
   {'id':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})
print(left)
print()
print(right)

   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5

   id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5


In [15]:
# 使用一个键合并两个数据帧
print(pd.merge(left, right, on='id'))

   id  Name_x subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5


In [16]:
# 使用多个键合并两个数据帧
print(pd.merge(left, right, on=['id', 'subject_id']))

   id  Name_x subject_id Name_y
0   4   Alice       sub6  Bryce
1   5  Ayoung       sub5  Betty


In [17]:
# 使用how参数合并
# left表示按照左边表格的on值进行合并
# 若右边表格在某序列上没数据，则填充None值
print(pd.merge(left, right, on='subject_id', how='left'))

   id_x  Name_x subject_id  id_y Name_y
0     1    Alex       sub1   NaN    NaN
1     2     Amy       sub2   1.0  Billy
2     3   Allen       sub4   2.0  Brian
3     4   Alice       sub6   4.0  Bryce
4     5  Ayoung       sub5   5.0  Betty


In [18]:
print(pd.merge(left, right, on='subject_id', how='right'))

   id_x  Name_x subject_id  id_y Name_y
0   2.0     Amy       sub2     1  Billy
1   3.0   Allen       sub4     2  Brian
2   NaN     NaN       sub3     3   Bran
3   4.0   Alice       sub6     4  Bryce
4   5.0  Ayoung       sub5     5  Betty


In [19]:
# outer表示‘并集’
print(pd.merge(left, right, on='subject_id', how='outer'))

   id_x  Name_x subject_id  id_y Name_y
0   1.0    Alex       sub1   NaN    NaN
1   2.0     Amy       sub2   1.0  Billy
2   3.0   Allen       sub4   2.0  Brian
3   4.0   Alice       sub6   4.0  Bryce
4   5.0  Ayoung       sub5   5.0  Betty
5   NaN     NaN       sub3   3.0   Bran


In [20]:
# inner表示交集
print(pd.merge(left, right, on='subject_id', how='inner'))


   id_x  Name_x subject_id  id_y Name_y
0     2     Amy       sub2     1  Billy
1     3   Allen       sub4     2  Brian
2     4   Alice       sub6     4  Bryce
3     5  Ayoung       sub5     5  Betty


In [21]:
# join()
df0 = pd.read_csv('data/sales.csv', sep=',', encoding='gbk')
df0.head()

序号 天气 是否周末 是否有促销 销量
0   1  坏    是     是  高
1   2  坏    是     是  高
2   3  坏    是     是  高
3   4  坏    否     是  高
4   5  坏    是     是  高

In [22]:
df1 = df0[3:9][['序号', '销量']]
df2 = df0[3:9][['是否周末']]
print(df1)
print(df2)

   序号 销量
3   4  高
4   5  高
5   6  高
6   7  高
7   8  高
8   9  高
  是否周末
3    否
4    是
5    否
6    是
7    是
8    是


In [23]:
df1.join(df2)

序号 销量 是否周末
3   4  高    否
4   5  高    是
5   6  高    否
6   7  高    是
7   8  高    是
8   9  高    是

In [24]:
# concat
one = pd.DataFrame({
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5'],
   'Marks_scored':[98,90,87,69,78]},
   index=[1,2,3,4,5])
two = pd.DataFrame({
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5'],
   'Marks_scored':[89,80,79,97,88]},
   index=[1,2,3,4,5])
print(pd.concat([one, two]))

     Name subject_id  Marks_scored
1    Alex       sub1            98
2     Amy       sub2            90
3   Allen       sub4            87
4   Alice       sub6            69
5  Ayoung       sub5            78
1   Billy       sub2            89
2   Brian       sub4            80
3    Bran       sub3            79
4   Bryce       sub6            97
5   Betty       sub5            88


In [25]:
# 在连接轴上创建一个层次化索引
print(pd.concat([one, two], keys=['x', 'y']))

       Name subject_id  Marks_scored
x 1    Alex       sub1            98
  2     Amy       sub2            90
  3   Allen       sub4            87
  4   Alice       sub6            69
  5  Ayoung       sub5            78
y 1   Billy       sub2            89
  2   Brian       sub4            80
  3    Bran       sub3            79
  4   Bryce       sub6            97
  5   Betty       sub5            88


In [26]:
# 输出结果不展示行索引
print(pd.concat([one, two], ignore_index=True))

     Name subject_id  Marks_scored
0    Alex       sub1            98
1     Amy       sub2            90
2   Allen       sub4            87
3   Alice       sub6            69
4  Ayoung       sub5            78
5   Billy       sub2            89
6   Brian       sub4            80
7    Bran       sub3            79
8   Bryce       sub6            97
9   Betty       sub5            88


In [27]:
# 按列合并对象
print(pd.concat([one, two], axis=1))

     Name subject_id  Marks_scored   Name subject_id  Marks_scored
1    Alex       sub1            98  Billy       sub2            89
2     Amy       sub2            90  Brian       sub4            80
3   Allen       sub4            87   Bran       sub3            79
4   Alice       sub6            69  Bryce       sub6            97
5  Ayoung       sub5            78  Betty       sub5            88


In [28]:
print(df1)
print(df2)

   序号 销量
3   4  高
4   5  高
5   6  高
6   7  高
7   8  高
8   9  高
  是否周末
3    否
4    是
5    否
6    是
7    是
8    是


In [29]:
# 未选择的属性用NaN填充
print(pd.concat([df1, df2]))

    序号   销量 是否周末
3  4.0    高  NaN
4  5.0    高  NaN
5  6.0    高  NaN
6  7.0    高  NaN
7  8.0    高  NaN
8  9.0    高  NaN
3  NaN  NaN    否
4  NaN  NaN    是
5  NaN  NaN    否
6  NaN  NaN    是
7  NaN  NaN    是
8  NaN  NaN    是


In [30]:
print(pd.concat([df1, df2], axis=1))

   序号 销量 是否周末
3   4  高    否
4   5  高    是
5   6  高    否
6   7  高    是
7   8  高    是
8   9  高    是


# 数据运算

In [31]:
arr = pd.array([1, 2, 3, 4, 5, 6])
# 求和
result_sum = np.sum(arr)
print(result_sum)
# 求乘积
result_prod = np.prod(arr)
print(result_prod)
# 两个数组合并
arr2 = np.arange(0, 12, 2)
print(arr)
print(arr2)
print(arr + arr2)

21
720
<IntegerArray>
[1, 2, 3, 4, 5, 6]
Length: 6, dtype: Int64
[ 0  2  4  6  8 10]
<IntegerArray>
[1, 4, 7, 10, 13, 16]
Length: 6, dtype: Int64


In [32]:
# 乘法（两个数组中的对应元素相乘）
print(arr)
print(arr2)
print(arr * arr2)

<IntegerArray>
[1, 2, 3, 4, 5, 6]
Length: 6, dtype: Int64
[ 0  2  4  6  8 10]
<IntegerArray>
[0, 4, 12, 24, 40, 60]
Length: 6, dtype: Int64


In [35]:
# e和log
a = np.array([1, np.e, np.e ** 2])
print(np.log(a))

[0. 1. 2.]


In [34]:
# log10()
b = np.array([100, 1000, 100000])
print(np.log10(b))

[2. 3. 5.]


In [40]:
c = np.exp(a)
c

array([   2.71828183,   15.15426224, 1618.17799191])