# 数据选择

In [2]:
import numpy as np
import pandas as pd

c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
c:\Users\OneRaise\miniconda3\Lib\site-packages\numpy\.libs\libopenblas64__v0.3.23-246-g3d31191b-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
# 一维数组的选择
a = np.array([1,2,3,4,5,6])

print(a[0])
print(a[-1])
print(a[0:2])
print(a[2:])
print(a[0:5:2])

1
6
[1 2]
[3 4 5 6]
[1 3 5]


In [4]:
# 二维数组的选择
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,2])
print(arr[0])
print(arr[:,0])

6
[1 2 3]
[1 4]


In [5]:
# 布尔值索引
bolling = np.array([True,False,False,True,True,False])
a[bolling]

array([1, 4, 5])

In [6]:
arr = np.arange(28).reshape((7,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [7]:
# 二维布尔索引
bolling2 = np.array([True,False,False,True,True,False,False])
arr[bolling2]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
# 花式索引
arr[arr > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [9]:
arr[arr > 14] = 0
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [11]:
# Pandas数据选择
# Series
s = pd.Series(data=[1,2,3,4,5,6],
              index=['a','b','a','a','a','c'])
s

a    1
b    2
a    3
a    4
a    5
c    6
dtype: int64

In [16]:
print(s['a'])
print(s[['b','c']])
print(s['b':'c'])
print(s['b':'c':2])

a    1
a    3
a    4
a    5
dtype: int64
b    2
c    6
dtype: int64
b    2
a    3
a    4
a    5
c    6
dtype: int64
b    2
a    4
c    6
dtype: int64


In [18]:
# DataFrame
df = pd.DataFrame(data=[[22, "北京", "律师" ],
                        [26, "四川成都", "工程师"],
                        [24, "江苏南京", "研究员"]],
                  index=["张某", "李某", "段某"],
                  columns=["age", "籍贯", "职业"])
df

age    籍贯   职业
张某   22    北京   律师
李某   26  四川成都  工程师
段某   24  江苏南京  研究员

In [26]:
print(df['age'], type(df['age']))  # 索引列
print(df['age']['张某'])  # 索引列，行
print(df['age'][0])  # 索引列，行
print(df['age'][df['age'].values == 22])

张某    22
李某    26
段某    24
Name: age, dtype: int64 <class 'pandas.core.series.Series'>
22
22
张某    22
Name: age, dtype: int64


C:\Users\OneRaise\AppData\Local\Temp\ipykernel_11208\1577797780.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df['age'][0])  # 索引列，行


In [29]:
# 这种格式默认是索引列，若想要索引行，必须使用[x:x]的形式
print(df['张某':'李某'])

    age    籍贯   职业
张某   22    北京   律师
李某   26  四川成都  工程师


# 数据合并

In [30]:
# merge()
left = pd.DataFrame({
   'id':[1,2,3,4,5],
   'Name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
   'subject_id':['sub1','sub2','sub4','sub6','sub5']})
right = pd.DataFrame(
   {'id':[1,2,3,4,5],
   'Name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
   'subject_id':['sub2','sub4','sub3','sub6','sub5']})
print(left)
print()
print(right)

   id    Name subject_id
0   1    Alex       sub1
1   2     Amy       sub2
2   3   Allen       sub4
3   4   Alice       sub6
4   5  Ayoung       sub5

   id   Name subject_id
0   1  Billy       sub2
1   2  Brian       sub4
2   3   Bran       sub3
3   4  Bryce       sub6
4   5  Betty       sub5


In [31]:
# 使用一个键合并两个数据帧
print(pd.merge(left, right, on='id'))

   id  Name_x subject_id_x Name_y subject_id_y
0   1    Alex         sub1  Billy         sub2
1   2     Amy         sub2  Brian         sub4
2   3   Allen         sub4   Bran         sub3
3   4   Alice         sub6  Bryce         sub6
4   5  Ayoung         sub5  Betty         sub5


In [32]:
# 使用多个键合并两个数据帧
print(pd.merge(left, right, on=['id', 'subject_id']))

   id  Name_x subject_id Name_y
0   4   Alice       sub6  Bryce
1   5  Ayoung       sub5  Betty


In [ ]:
# 使用how参数合并
